```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

# =========================
# STAGE 1 - VALIDATE
# =========================
- stage: Validate
<<<<<<< HEAD
  displayName: Terraform Validate

  jobs:
  - job: ValidateTerraform

    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'azure-terraform-connection'
        KeyVaultName: 'hubspoke-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.9.8'

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
        backendServiceArm: 'azure-terraform-connection'
        backendAzureRmResourceGroupName: 'Tr-2.0-ResourceGroup'
        backendAzureRmStorageAccountName: 'debstorageaccountbackend'
        backendAzureRmContainerName: 'newtfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

=======
  jobs:
  - job: ValidateTerraform
    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'azure-terraform-connection'
        KeyVaultName: 'hubspoke-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.9.8'

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
        backendServiceArm: 'azure-terraform-connection'
        backendAzureRmResourceGroupName: 'Tr-2.0-ResourceGroup'
        backendAzureRmStorageAccountName: 'debstorageaccountbackend'
        backendAzureRmContainerName: 'newtfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

>>>>>>> 93fa0c9 (added multi-stage terraform cd pipeline)
    - task: TerraformTaskV4@4
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
<<<<<<< HEAD

# =========================
# STAGE 2 - PLAN
# =========================
- stage: Plan
  displayName: Terraform Plan
  dependsOn: Validate

  jobs:
  - job: TerraformPlan

=======

# =========================
# STAGE 2 - PLAN
# =========================
- stage: Plan
  dependsOn: Validate

  jobs:
  - job: TerraformPlan
>>>>>>> 93fa0c9 (added multi-stage terraform cd pipeline)
    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'azure-terraform-connection'
        KeyVaultName: 'hubspoke-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.9.8'

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
        backendServiceArm: 'azure-terraform-connection'
        backendAzureRmResourceGroupName: 'Tr-2.0-ResourceGroup'
        backendAzureRmStorageAccountName: 'debstorageaccountbackend'
        backendAzureRmContainerName: 'newtfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
        environmentServiceNameAzureRM: 'azure-terraform-connection'

        commandOptions: >
          -var="admin_username=$(admin-username)"
          -var="admin_password=$(admin-password)"
          -var="admin_public_ip=$(admin-public-ip)"
          -var="public_key=$(public-key)"

# =========================
# STAGE 3 - APPLY
# =========================
- stage: Apply
<<<<<<< HEAD
  displayName: Terraform Apply
=======
>>>>>>> 93fa0c9 (added multi-stage terraform cd pipeline)
  dependsOn: Plan

  jobs:
  - deployment: TerraformApply
<<<<<<< HEAD

    pool:
      vmImage: ubuntu-latest

=======
>>>>>>> 93fa0c9 (added multi-stage terraform cd pipeline)
    environment: prod

    strategy:
      runOnce:
        deploy:
<<<<<<< HEAD

=======
>>>>>>> 93fa0c9 (added multi-stage terraform cd pipeline)
          steps:

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'azure-terraform-connection'
              KeyVaultName: 'hubspoke-kv'
              SecretsFilter: '*'
              RunAsPreJob: true

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.9.0'

          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
              backendServiceArm: 'azure-terraform-connection'
              backendAzureRmResourceGroupName: 'Tr-2.0-ResourceGroup'
              backendAzureRmStorageAccountName: 'debstorageaccountbackend'
              backendAzureRmContainerName: 'newtfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

          - task: TerraformTaskV4@4
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/hub-spoke-TF'
              environmentServiceNameAzureRM: 'azure-terraform-connection'

              commandOptions: >
                -auto-approve
                -var="admin_username=$(admin-username)"
                -var="admin_password=$(admin-password)"
                -var="admin_public_ip=$(admin-public-ip)"
<<<<<<< HEAD
                -var="public_key=$(public-key)"
=======
                -var="public_key=$(public-key)"
```
>>>>>>> 93fa0c9 (added multi-stage terraform cd pipeline)
