trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Validate
  displayName: Terraform Validate
  jobs:
  - job: ValidateTerraform
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'azure-terraform-connection'
        KeyVaultName: 'hubspoke-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.8.5'

    - script: |
        export PATH="$PATH:/opt/hostedtoolcache/terraform/1.8.5/x64"
        cd $(System.DefaultWorkingDirectory)/hub-spoke-TF
        terraform version
        terraform init \
          -backend-config="storage_account_name=debstorageaccountbackend" \
          -backend-config="container_name=newtfstate" \
          -backend-config="key=dev.terraform.tfstate" \
          -backend-config="resource_group_name=Tr-2.0-ResourceGroup" \
          -backend-config="subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
          -backend-config="tenant_id=$(AZURE_TENANT_ID)"
      displayName: 'Terraform Init'
      env:
        AZURE_SUBSCRIPTION_ID: $(azure-terraform-connection-subscription-id)
        AZURE_TENANT_ID: $(azure-terraform-connection-tenant-id)
      continueOnError: false

    - script: |
        export PATH="$PATH:/opt/hostedtoolcache/terraform/1.8.5/x64"
        cd $(System.DefaultWorkingDirectory)/hub-spoke-TF
        terraform validate
      displayName: 'Terraform Validate'
      continueOnError: false

- stage: Plan
  displayName: Terraform Plan
  dependsOn: Validate
  jobs:
  - job: TerraformPlan
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'azure-terraform-connection'
        KeyVaultName: 'hubspoke-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.8.5'

    - script: |
        export PATH="$PATH:/opt/hostedtoolcache/terraform/1.8.5/x64"
        cd $(System.DefaultWorkingDirectory)/hub-spoke-TF
        terraform version
        terraform init \
          -backend-config="storage_account_name=debstorageaccountbackend" \
          -backend-config="container_name=newtfstate" \
          -backend-config="key=dev.terraform.tfstate" \
          -backend-config="resource_group_name=Tr-2.0-ResourceGroup" \
          -backend-config="subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
          -backend-config="tenant_id=$(AZURE_TENANT_ID)"
      displayName: 'Terraform Init'
      env:
        AZURE_SUBSCRIPTION_ID: $(azure-terraform-connection-subscription-id)
        AZURE_TENANT_ID: $(azure-terraform-connection-tenant-id)
      continueOnError: false

    - script: |
        export PATH="$PATH:/opt/hostedtoolcache/terraform/1.8.5/x64"
        cd $(System.DefaultWorkingDirectory)/hub-spoke-TF
        terraform plan \
          -var="admin_username=$(admin-username)" \
          -var="admin_password=$(admin-password)" \
          -var="admin_public_ip=$(admin-public-ip)" \
          -var="public_key=$(public-key)" \
          -out=tfplan
      displayName: 'Terraform Plan'
      env:
        ARM_SUBSCRIPTION_ID: $(azure-terraform-connection-subscription-id)
        ARM_TENANT_ID: $(azure-terraform-connection-tenant-id)
      continueOnError: false

- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan
  jobs:
  - deployment: TerraformApply
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'azure-terraform-connection'
              KeyVaultName: 'hubspoke-kv'
              SecretsFilter: '*'
              RunAsPreJob: true

          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.8.5'

          - script: |
              export PATH="$PATH:/opt/hostedtoolcache/terraform/1.8.5/x64"
              cd $(System.DefaultWorkingDirectory)/hub-spoke-TF
              terraform version
              terraform init \
                -backend-config="storage_account_name=debstorageaccountbackend" \
                -backend-config="container_name=newtfstate" \
                -backend-config="key=dev.terraform.tfstate" \
                -backend-config="resource_group_name=Tr-2.0-ResourceGroup" \
                -backend-config="subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
                -backend-config="tenant_id=$(AZURE_TENANT_ID)"
            displayName: 'Terraform Init'
            env:
              AZURE_SUBSCRIPTION_ID: $(azure-terraform-connection-subscription-id)
              AZURE_TENANT_ID: $(azure-terraform-connection-tenant-id)
            continueOnError: false

          - script: |
              export PATH="$PATH:/opt/hostedtoolcache/terraform/1.8.5/x64"
              cd $(System.DefaultWorkingDirectory)/hub-spoke-TF
              terraform apply \
                -auto-approve \
                -var="admin_username=$(admin-username)" \
                -var="admin_password=$(admin-password)" \
                -var="admin_public_ip=$(admin-public-ip)" \
                -var="public_key=$(public-key)"
            displayName: 'Terraform Apply'
            env:
              ARM_SUBSCRIPTION_ID: $(azure-terraform-connection-subscription-id)
              ARM_TENANT_ID: $(azure-terraform-connection-tenant-id)
            continueOnError: false