trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev

  values:
  - dev
  - uat
  - prod

stages:

- stage: Destroy
  displayName: Terraform Destroy

  jobs:

  - deployment: TerraformDestroy

    displayName: Destroy Infrastructure

    environment: ${{ parameters.environment }}

    strategy:
      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'azure-terraform-connection'
              KeyVaultName: 'hubspoke-kv'
              SecretsFilter: '*'
              RunAsPreJob: true

          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.9.8'

          - task: TerraformTaskV4@4
            displayName: Terraform Init

            inputs:
              provider: 'azurerm'
              command: 'init'

              workingDirectory: '$(System.DefaultWorkingDirectory)'

              backendServiceArm: 'azure-terraform-connection'

              backendAzureRmResourceGroupName: 'Tr-2.0-ResourceGroup'

              backendAzureRmStorageAccountName: 'debstorageaccountbackend'

              backendAzureRmContainerName: 'newtfstate'

              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

          - task: TerraformTaskV4@4
            displayName: Terraform Destroy

            inputs:
              provider: 'azurerm'
              command: 'destroy'

              workingDirectory: '$(System.DefaultWorkingDirectory)'

              environmentServiceNameAzureRM: 'azure-terraform-connection'

              commandOptions: >
                -auto-approve
                -var-file="$(System.DefaultWorkingDirectory)/${{ parameters.environment }}.tfvars"
                -var="admin_username=$(admin-username)"
                -var="admin_password=$(admin-password)"
                -var="admin_public_ip=$(admin-public-ip)"
                -var="public_key=$(public-key)"
